### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by manifarizi** [dhanoosu/TkTerm#1]
How i can fix this?
full error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Darkoak\Desktop\Text-Editor-master\TkTerm-master\tkterm.py", line 874, in __init__
    def __init__(self, parent, *args, **kwargs):
NameError: name 'sys' is not defined
>>> terminal.pack(fill=BOTH, expand=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'terminal' is not defined. Did you mean: 'Terminal'?
>>>
>>> root.mainloop()

**Comment by dhanoosu** [comment]
Can you try adding

`import sys`

at the very top of tkterm.py
